language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  include:
    - stage: deploy
      rust: stable
      deploy:
        provider: cargo
        token: $CRATES_IO_API_TOKEN

stages:
  - test
  - name: deploy
    if: tag =~ ^v[0-9]+(?:\.[0-9]+){2}$
